#!/usr/local/bin/python

# set server timezone in UTC before time module imported
__import__('os').environ['TZ'] = 'UTC'
import odoo
import sys
import os
import logging

_logger = logging.getLogger(__name__)

if __name__ == "__main__":
    odoo_saas_path = os.environ.get('ODOO_SAAS_PATH')
    if odoo_saas_path:
        # TODO we could make this an env argument
        sys.path.insert(1, odoo_saas_path)
        import odoo_server_patch
    odoo.cli.main()
