#!/bin/bash

# Patch odoo server.py
cp -f $RESOURCES/server.py /home/odoo/.local/lib/python2.7/site-packages/openerp/cli/server.py
chown odoo.odoo /home/odoo/.local/lib/python2.7/site-packages/openerp/cli/server.py
