#!/usr/local/bin/python
import sys, os
# EASY-INSTALL-DEV-SCRIPT: 'odoo==14.0','odoo'
__requires__ = 'odoo==18.0'
__import__('pkg_resources').require('odoo==18.0')
__file__ = '/home/odoo/src/odoo/setup/odoo'
odoo_saas_path = os.environ.get('ODOO_SAAS_PATH')

if odoo_saas_path:
    # TODO we could make this an env argument
    sys.path.insert(1, odoo_saas_path)
    import odoo_server_patch

with open(__file__) as f:
    exec(compile(f.read(), __file__, 'exec'))
