#!/bin/bash
set -ex

DOCKER_IMAGE=${DOCKER_REPO/#index.docker.io\/}

MAXMIND_LICENSE_USR=${MAXMIND_LICENSE_USER:-1011117}
# Force to rebuild the if content is modified
MAXMIND_UPDATE=$(curl -I -sL -u ${MAXMIND_LICENSE_USR}:${MAXMIND_LICENSE_KEY} 'https://download.maxmind.com/geoip/databases/GeoLite2-City/download?suffix=tar.gz' | grep -i "Last-Modified" | awk -F': ' '{print $2}')

# Force to rebuild the first layer one a month
ODOO_BUILD=${ODOO_BUILD:-$(date -u +%Y%m)}
ODOO_BY_ADHOC_BUILD=${ODOO_BY_ADHOC_BUILD:-0}

# --no-cache-filter python:3.10-slim-bookworm  \

docker buildx build \
    --build-arg MAXMIND_LICENSE_KEY="$MAXMIND_LICENSE_KEY" \
    --build-arg MAXMIND_LICENSE_USER="$MAXMIND_LICENSE_USR" \
    --build-arg MAXMIND_UPDATE="$MAXMIND_UPDATE" \
    --build-arg ODOO_VERSION="18.0" \
    --build-arg ODOO_BUILD="$ODOO_BUILD" \
    --build-arg SAAS_PROVIDER_URL="$SAAS_PROVIDER_URL" \
    --build-arg SAAS_PROVIDER_TOKEN="$SAAS_PROVIDER_TOKEN" \
    --build-arg GITHUB_BOT_TOKEN="$GITHUB_BOT_TOKEN" \
    --build-arg ODOO_BY_ADHOC_BUILD="$ODOO_BY_ADHOC_BUILD" \
    --target prod \
    -t "$DOCKER_REPO:$DOCKER_TAG" \
    .

docker buildx build \
    --build-arg MAXMIND_LICENSE_KEY="$MAXMIND_LICENSE_KEY" \
    --build-arg MAXMIND_LICENSE_USER="$MAXMIND_LICENSE_USR" \
    --build-arg MAXMIND_UPDATE="$MAXMIND_UPDATE" \
    --build-arg ODOO_VERSION="18.0" \
    --build-arg ODOO_BUILD="$ODOO_BUILD" \
    --build-arg SAAS_PROVIDER_URL="$SAAS_PROVIDER_URL" \
    --build-arg SAAS_PROVIDER_TOKEN="$SAAS_PROVIDER_TOKEN" \
    --build-arg GITHUB_BOT_TOKEN="$GITHUB_BOT_TOKEN" \
    --build-arg ODOO_BY_ADHOC_BUILD="$ODOO_BY_ADHOC_BUILD" \
    --target dev \
    -t "$DOCKER_REPO:$DOCKER_TAG.dev" \
    .
