#!/bin/bash
set -ex

# Version control tags
# We append BUILD_DATE to the image tag.

BUILD_DATE=`date -u +%Y.%m.%d`

for target in adhoc adhoc-e; do

    # Don't build base if BUILD_TAG_BASE != true
    if [ "$target" == "adhoc-e" ] && [ -z "$BUILD_TAG_ENTERPRISE" ]; then
        continue
    fi

    BASE_IMAGE_TAG="$DOCKER_TAG"
    if [ "$target" == "adhoc-e" ]; then
        BASE_IMAGE_TAG="${BASE_IMAGE_TAG}-enterprise"
    fi

	TAG="$DOCKER_REPO:$BASE_IMAGE_TAG"
	NEWTAG="$DOCKER_REPO:$BASE_IMAGE_TAG.$BUILD_DATE"
	docker tag "$TAG" "$NEWTAG"
    docker push "$NEWTAG"
done
