#!/usr/bin/env python
import os
import datetime
from subprocess import check_call


def env(key):
    return os.environ.get(key, "")


BUILD_TAG_COMMUNITY = env("BUILD_TAG_COMMUNITY")
BUILD_TAG_ENTERPRISE = env("BUILD_TAG_ENTERPRISE")
DOCKER_REPO = env("DOCKER_REPO")
DOCKER_TAG = env("DOCKER_TAG")
BUILD_DATE = datetime.date.today().strftime("%Y.%m.%d")

TAG = "%s:%s" % (DOCKER_REPO, DOCKER_TAG)
VERSION_TAG = "%s.%s" % (TAG, BUILD_DATE)

if BUILD_TAG_COMMUNITY:
    check_call(["docker", "tag", TAG, VERSION_TAG])
    check_call(["docker", "push", VERSION_TAG])

if BUILD_TAG_ENTERPRISE and DOCKER_TAG not in ["7.0", "8.0"]:
    EE_TAG = "%s-enterprise" % TAG
    EE_VERSION_TAG = "%s-enterprise" % VERSION_TAG
    check_call(["docker", "tag", EE_TAG, EE_VERSION_TAG])
    check_call(["docker", "push", EE_VERSION_TAG])
