#!/bin/bash
set -ex

if [ ! -z "$BUILD_TAG_COMMUNITY" ]; then
    docker push "$DOCKER_REPO:$DOCKER_TAG"
fi

if [ ! -z "$BUILD_TAG_ENTERPRISE" ]; then
    docker push "$DOCKER_REPO:$DOCKER_TAG-enterprise"
fi
